python 14_N1S1_filter.py S1-0Gy-1.combination.Mutect_Strelka_union.vcf.readinfo.filtered.vcf
python 14_N1S1_filter.py S1-0Gy-2.combination.Mutect_Strelka_union.vcf.readinfo.filtered.vcf
python 14_N1S1_filter.py S1-1Gy-1.combination.Mutect_Strelka_union.vcf.readinfo.filtered.vcf
python 14_N1S1_filter.py S1-1Gy-2.combination.Mutect_Strelka_union.vcf.readinfo.filtered.vcf
python 14_N1S1_filter.py S1-2Gy-1.combination.Mutect_Strelka_union.vcf.readinfo.filtered.vcf
python 14_N1S1_filter.py S1-2Gy-2.combination.Mutect_Strelka_union.vcf.readinfo.filtered.vcf
python 14_N1S1_filter.py S1-4Gy-1.combination.Mutect_Strelka_union.vcf.readinfo.filtered.vcf
python 14_N1S1_filter.py S1-4Gy-2.combination.Mutect_Strelka_union.vcf.readinfo.filtered.vcf
python 14_N1S1_filter.py S1-8Gy-1.combination.Mutect_Strelka_union.vcf.readinfo.filtered.vcf
