ln -s dirams_8by1Gy_S2.varscan.indel.vcf 8Gy_2_S02_S.varscan.indel.vcf
ln -s dirams_8by1Gy_S1.varscan.indel.vcf 8Gy_2_S01_S.varscan.indel.vcf
ln -s dirams_lowdose_S2.varscan.indel.vcf L3_S02_Single.varscan.indel.vcf
ln -s dirams_20Gy_S2.varscan.indel.vcf 20Gy_1_S03_S.varscan.indel.vcf
ln -s dirams_20Gy_S1.varscan.indel.vcf 20Gy_1_S01_S.varscan.indel.vcf
ln -s dirams_8by4Gy_S1.varscan.indel.vcf 2Gy_2_S03_S.varscan.indel.vcf
ln -s dirams_lowdose_S1.varscan.indel.vcf L3_S01_Single.varscan.indel.vcf
ln -s dirams_8by4Gy_S2.varscan.indel.vcf 2Gy_2_S04_S.varscan.indel.vcf
ln -s C3SO3_diramslow.varscan.indel.vcf C3SO3.varscan.indel.vcf
