sh 00_human_b37_script_mpileup.sh hs_study5_colon_control_HCNor2_BO
sh 00_human_b37_script_mpileup.sh hs_study5_colon_control_HCNor2_bulktissue
sh 00_human_b37_script_mpileup.sh hs_study5_colon_control_HCNor2_SC4
sh 00_human_b37_script_mpileup.sh hs_study5_colon_control_HCNor2_SC5
sh 00_human_b37_script_mpileup.sh hs_study5_colon_control_HCNor2_SC6
