sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam male_panc_L3SO4 mm_study3_pancreas_Lowdose_SO2
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam mm_study3_pancreas_Lowdose_SO2 male_panc_L3SO4
