sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Panc_20Gy1_SO2 Liver_20Gy_1_G
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Liver_20Gy1_SO1 Liver_20Gy_1_G
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Liver_20Gy1_SO2 Liver_20Gy_1_G
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Liver_20Gy1_SO4 Liver_20Gy_1_G
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Panc_8Gy1_SO1 Panc_8Gy1_BO
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Panc_8Gy1_SO3 Panc_8Gy1_BO
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Liver_8Gy1_SO3 Panc_8Gy1_BO
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Liver_8Gy1_SO5 Panc_8Gy1_BO
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Panc_2Gy2_SO2 Liver_2Gy_2_G
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Liver_2Gy2_SO1 Liver_2Gy_2_G
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Liver_2Gy2_SO2 Liver_2Gy_2_G
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Liver_2Gy2_SO4 Liver_2Gy_2_G
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam C3SO3 Panc_C3_BO
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Liver_C3SO1 Panc_C3_BO
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam Liver_C3SO2 Panc_C3_BO
