sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam S1-0Gy-1 N1spleen
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam S1-4Gy-2 N1spleen
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam S1-1Gy-2 N1spleen
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam S1-4Gy-1 N1spleen
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam S1-2Gy-1 N1spleen
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam S1-0Gy-2 N1spleen
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam S1-8Gy-1 N1spleen
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam S1-1Gy-1 N1spleen
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam S1-2Gy-2 N1spleen
