python 04_filter_somatic.py breast_mother.delly.vcf
python 04_filter_somatic.py dirams_20Gy_S1.delly.vcf
python 04_filter_somatic.py dirams_20Gy_S2.delly.vcf
python 04_filter_somatic.py dirams_8by1Gy_S1.delly.vcf
python 04_filter_somatic.py dirams_8by1Gy_S2.delly.vcf
python 04_filter_somatic.py dirams_8by4Gy_S1.delly.vcf
python 04_filter_somatic.py dirams_8by4Gy_S2.delly.vcf
python 04_filter_somatic.py dirams_lowdose_S1.delly.vcf
python 04_filter_somatic.py dirams_lowdose_S2.delly.vcf
