sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Panc_20Gy1_SO2 Liver_20Gy_1_G
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Liver_20Gy1_SO1 Liver_20Gy_1_G
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Liver_20Gy1_SO2 Liver_20Gy_1_G
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Liver_20Gy1_SO4 Liver_20Gy_1_G
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Panc_8Gy1_SO1 Panc_8Gy1_BO
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Panc_8Gy1_SO3 Panc_8Gy1_BO
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Liver_8Gy1_SO3 Panc_8Gy1_BO
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Liver_8Gy1_SO5 Panc_8Gy1_BO
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Panc_2Gy2_SO2 Liver_2Gy_2_G
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Liver_2Gy2_SO1 Liver_2Gy_2_G
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Liver_2Gy2_SO2 Liver_2Gy_2_G
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Liver_2Gy2_SO4 Liver_2Gy_2_G
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam C3SO3 Panc_C3_BO
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Liver_C3SO1 Panc_C3_BO
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam Liver_C3SO2 Panc_C3_BO
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam S1P13_2-3 N1spleen
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam S1P13_0-4 N1spleen
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam S1P13_0-5 N1spleen
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam S1P12_0-7 N1spleen
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam S1P12_0-3 N1spleen
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_1Gy-3 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_1Gy-4 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_2Gy-6 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_1Gy_1-P20 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_1Gy-5 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_0Gy-3 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_P19_4Gy-4 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_P19_4Gy-5 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_P19_2Gy-8 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_P19_0Gy-1 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_1Gy-6 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_1Gy-2 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_2Gy-7 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_P19_4Gy-2 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_2Gy-1 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_2Gy-5 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_2Gy-2 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_2Gy-3 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_2Gy-4 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam male_panc_L3SO4 male_panc_L3BO
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam male_panc_L3SO5 male_panc_L3BO
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3P7 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B8 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3-0_0Gy_2 Spleen_m3
sh 05_1_script_filter_MH_MP.sh /home/users/team_projects/Radiation_signature/02_bam B3P16_0Gy_4 Spleen_m3
