cp mm_study4_breast_sham_SO2.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_breast_sham_SO3.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_stomach_sham_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_stomach_sham_SO2.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_stomach_sham_SO3.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_stomach_IR_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_stomach_IR_SO2.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_stomach_IR_SO3.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_liver_IR_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_liver_IR_SO2.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_liver_sham_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_liver_sham_SO2.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_liver_sham_SO3.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_colon_sham_SO3.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_SI_IR_SO3.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_SI_IR_SO4.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_SI_sham_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_fallopian_sham_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study4_fallopian_sham_SO2.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
cp mm_study2_pancreas_sham_C3SO1SO1_normoxia_SO2.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
