mv mm_study4_breast_sham_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study4_breast_IR_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study4_breast_IR_SO2.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study4_breast_IR_SO3.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study4_liver_IR_SO3.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study4_colon_sham_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study4_colon_sham_SO2.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study4_colon_IR_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study4_colon_IR_SO2.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study4_colon_IR_SO3.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study4_SI_IR_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study4_fallopian_IR_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study4_fallopian_IR_SO2.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study2_pancreas_sham_C3SO1SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
mv mm_study2_pancreas_sham_C3SO1SO1_normoxia_SO1.delly.vcf /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/
