/home/users/team_projects/Radiation_signature/02_bam/mm_study4_breast_sham_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Normal-spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_breast_IR_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/IR-spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_breast_IR_SO2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/IR-spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_breast_IR_SO3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/IR-spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_liver_IR_SO3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/IR-spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_colon_sham_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Normal-spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_colon_sham_SO2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Normal-spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_colon_IR_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/IR-spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_colon_IR_SO2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/IR-spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_colon_IR_SO3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/IR-spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_SI_IR_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_2nd_IR.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_fallopian_IR_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/IR-spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_fallopian_IR_SO2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/IR-spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study2_pancreas_sham_C3SO1SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Panc_C3_BO.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study2_pancreas_sham_C3SO1SO1_normoxia_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Panc_C3_BO.s.md.ir.br.bam
