#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -j oe
#PBS -o /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter/qsub_sdout/000_1_run_invitro_1.sh.sdout
cd /home/users/jhyouk/06_mm10_SNUH_radiation/33_SV_filter
sh 000_SV_anno_filter.sh S1-4Gy-2 /home/users/team_projects/Radiation_signature/02_bam/S1-4Gy-2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam 190225_delly_panelofnormal_1_9.vcf /home/users/team_projects/Radiation_signature/02_bam/N1-S1.s.md.ir.br.bam
sh 000_SV_anno_filter.sh S1-8Gy-1 /home/users/team_projects/Radiation_signature/02_bam/S1-8Gy-1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam 190225_delly_panelofnormal_1_9.vcf /home/users/team_projects/Radiation_signature/02_bam/N1-S1.s.md.ir.br.bam
sh 000_SV_anno_filter.sh S1-1Gy-2 /home/users/team_projects/Radiation_signature/02_bam/S1-1Gy-2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam 190225_delly_panelofnormal_1_9.vcf /home/users/team_projects/Radiation_signature/02_bam/N1-S1.s.md.ir.br.bam
sh 000_SV_anno_filter.sh S1-2Gy-2 /home/users/team_projects/Radiation_signature/02_bam/S1-2Gy-2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam 190225_delly_panelofnormal_1_9.vcf /home/users/team_projects/Radiation_signature/02_bam/N1-S1.s.md.ir.br.bam
sh 000_SV_anno_filter.sh S1-0Gy-2 /home/users/team_projects/Radiation_signature/02_bam/S1-0Gy-2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam 190225_delly_panelofnormal_1_9.vcf /home/users/team_projects/Radiation_signature/02_bam/N1-S1.s.md.ir.br.bam
sh 000_SV_anno_filter.sh S1-2Gy-1 /home/users/team_projects/Radiation_signature/02_bam/S1-2Gy-1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam 190225_delly_panelofnormal_1_9.vcf /home/users/team_projects/Radiation_signature/02_bam/N1-S1.s.md.ir.br.bam
sh 000_SV_anno_filter.sh S1-4Gy-1 /home/users/team_projects/Radiation_signature/02_bam/S1-4Gy-1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam 190225_delly_panelofnormal_1_9.vcf /home/users/team_projects/Radiation_signature/02_bam/N1-S1.s.md.ir.br.bam
sh 000_SV_anno_filter.sh S1-1Gy-1 /home/users/team_projects/Radiation_signature/02_bam/S1-1Gy-1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam 190225_delly_panelofnormal_1_9.vcf /home/users/team_projects/Radiation_signature/02_bam/N1-S1.s.md.ir.br.bam
sh 000_SV_anno_filter.sh S1-0Gy-1 /home/users/team_projects/Radiation_signature/02_bam/S1-0Gy-1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam 190225_delly_panelofnormal_1_9.vcf /home/users/team_projects/Radiation_signature/02_bam/N1-S1.s.md.ir.br.bam
sh 000_SV_anno_filter.sh S1P13_0-4 /home/users/team_projects/Radiation_signature/02_bam/S1P13_0-4.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam 190225_delly_panelofnormal_1_9.vcf /home/users/team_projects/Radiation_signature/02_bam/N1-S1.s.md.ir.br.bam