sh 00_human_b37_Delly.sh /home/users/team_projects/Radiation_signature/05_bam_human_sample_GRCh37 hs_study5_colon_control_HCNor1_SC4_2nd HCNor1
sh 00_human_b37_Delly.sh /home/users/team_projects/Radiation_signature/05_bam_human_sample_GRCh37 hs_study5_colon_control_HCNor1_SC5_2nd HCNor1
