sh 00_human_b37_Delly.sh /home/users/team_projects/Radiation_signature/05_bam_human_sample_GRCh37 hs_study5_colon_control_HCNor2_SC1 hs_study5_colon_control_HCNor2_bulktissue
sh 00_human_b37_Delly.sh /home/users/team_projects/Radiation_signature/05_bam_human_sample_GRCh37 hs_study5_colon_control_HCNor2_SC2 hs_study5_colon_control_HCNor2_bulktissue
sh 00_human_b37_Delly.sh /home/users/team_projects/Radiation_signature/05_bam_human_sample_GRCh37 hs_study5_colon_control_HCNor2_SC3 hs_study5_colon_control_HCNor2_bulktissue
sh 00_human_b37_Delly.sh /home/users/team_projects/Radiation_signature/05_bam_human_sample_GRCh37 hs_study5_colon_control_HCNor2_SC4 hs_study5_colon_control_HCNor2_bulktissue
sh 00_human_b37_Delly.sh /home/users/team_projects/Radiation_signature/05_bam_human_sample_GRCh37 hs_study5_colon_control_HCNor2_SC5 hs_study5_colon_control_HCNor2_bulktissue
sh 00_human_b37_Delly.sh /home/users/team_projects/Radiation_signature/05_bam_human_sample_GRCh37 hs_study5_colon_control_HCNor2_SC6 hs_study5_colon_control_HCNor2_bulktissue
