sh 00_human_Delly.sh /home/users/team_projects/Radiation_signature/04_bam_human_sample hs_study5_colon_IR_HCIR1_SC1 HCIR1
sh 00_human_Delly.sh /home/users/team_projects/Radiation_signature/04_bam_human_sample hs_study5_colon_IR_HCIR1_SC2 HCIR1
sh 00_human_Delly.sh /home/users/team_projects/Radiation_signature/04_bam_human_sample hs_study5_colon_IR_HCIR1_SC6 HCIR1
sh 00_human_Delly.sh /home/users/team_projects/Radiation_signature/04_bam_human_sample hs_study5_colon_control_HCNor1_SC4 hs_study5_germline_HCNor1
sh 00_human_Delly.sh /home/users/team_projects/Radiation_signature/04_bam_human_sample hs_study5_colon_control_HCNor1_SC5 hs_study5_germline_HCNor1
