sh 00_human_b37_Delly.sh /home/users/team_projects/Radiation_signature/05_bam_human_sample_GRCh37 hs_study5_colon_control_HCNor1_SC4 hs_study5_colon_control_HCNor1_SC5
sh 00_human_b37_Delly.sh /home/users/team_projects/Radiation_signature/05_bam_human_sample_GRCh37 hs_study5_colon_control_HCNor1_SC5 hs_study5_colon_control_HCNor1_SC4
