sh 02_merge_delly.sh hs_study5_colon_control_HCNor2_SC1
sh 02_merge_delly.sh hs_study5_colon_control_HCNor2_SC2
sh 02_merge_delly.sh hs_study5_colon_control_HCNor2_SC3
sh 02_merge_delly.sh hs_study5_colon_control_HCNor2_SC4
sh 02_merge_delly.sh hs_study5_colon_control_HCNor2_SC5
sh 02_merge_delly.sh hs_study5_colon_control_HCNor2_SC6
