sh 02_merge_delly.sh hs_study5_colon_IR_HCIR1_SC1
sh 02_merge_delly.sh hs_study5_colon_IR_HCIR1_SC2
sh 02_merge_delly.sh hs_study5_colon_IR_HCIR1_SC6
sh 02_merge_delly.sh hs_study5_colon_control_HCNor1_SC4
sh 02_merge_delly.sh hs_study5_colon_control_HCNor1_SC5
