sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.rg.bam /home/users/team_projects/Radiation_signature/02_bam/S1P13_2-3.s.md.ir.br.bam S1P13_2-3
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.rg.bam /home/users/team_projects/Radiation_signature/02_bam/S1P13_0-4.s.md.ir.br.bam S1P13_0-4
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.rg.bam /home/users/team_projects/Radiation_signature/02_bam/S1P13_0-5.s.md.ir.br.bam S1P13_0-5
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.rg.bam /home/users/team_projects/Radiation_signature/02_bam/S1P12_0-7.s.md.ir.br.bam S1P12_0-7
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.rg.bam /home/users/team_projects/Radiation_signature/02_bam/S1P12_0-3.s.md.ir.br.bam S1P12_0-3
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_1Gy-3.s.md.ir.br.bam B3-0_1Gy-3
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_1Gy-4.s.md.ir.br.bam B3-0_1Gy-4
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_2Gy-6.s.md.ir.br.bam B3-0_2Gy-6
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_1Gy_1-P20.s.md.ir.br.bam B3-0_1Gy_1-P20
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_1Gy-5.s.md.ir.br.bam B3-0_1Gy-5
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_0Gy-3.s.md.ir.br.bam B3-0_0Gy-3
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_P19_4Gy-4.s.md.ir.br.bam B3-0_P19_4Gy-4
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_P19_4Gy-5.s.md.ir.br.bam B3-0_P19_4Gy-5
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_P19_2Gy-8.s.md.ir.br.bam B3-0_P19_2Gy-8
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_P19_0Gy-1.s.md.ir.br.bam B3-0_P19_0Gy-1
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_1Gy-6.s.md.ir.br.bam B3-0_1Gy-6
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_1Gy-2.s.md.ir.br.bam B3-0_1Gy-2
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_2Gy-7.s.md.ir.br.bam B3-0_2Gy-7
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_P19_4Gy-2.s.md.ir.br.bam B3-0_P19_4Gy-2
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_2Gy-1.s.md.ir.br.bam B3-0_2Gy-1
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_2Gy-5.s.md.ir.br.bam B3-0_2Gy-5
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_2Gy-2.s.md.ir.br.bam B3-0_2Gy-2
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_2Gy-3.s.md.ir.br.bam B3-0_2Gy-3
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/B3-0_2Gy-4.s.md.ir.br.bam B3-0_2Gy-4
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/male_panc_L3BO.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/male_panc_L3SO4.s.md.ir.br.bam male_panc_L3SO4
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/male_panc_L3BO.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/male_panc_L3SO5.s.md.ir.br.bam male_panc_L3SO5
