sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/S1-0Gy-1.s.md.ir.br.bam S1-0Gy-1
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/S1-4Gy-2.s.md.ir.br.bam S1-4Gy-2
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/S1-1Gy-2.s.md.ir.br.bam S1-1Gy-2
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/S1-4Gy-1.s.md.ir.br.bam S1-4Gy-1
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/S1-2Gy-1.s.md.ir.br.bam S1-2Gy-1
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/S1-0Gy-2.s.md.ir.br.bam S1-0Gy-2
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/S1-8Gy-1.s.md.ir.br.bam S1-8Gy-1
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/S1-1Gy-1.s.md.ir.br.bam S1-1Gy-1
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/S1-2Gy-2.s.md.ir.br.bam S1-2Gy-2
