sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Liver_20Gy_1_G.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Panc_20Gy1_SO2.s.md.ir.br.bam Panc_20Gy1_SO2
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Liver_20Gy_1_G.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Liver_20Gy1_SO1.s.md.ir.br.bam Liver_20Gy1_SO1
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Liver_20Gy_1_G.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Liver_20Gy1_SO2.s.md.ir.br.bam Liver_20Gy1_SO2
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Liver_20Gy_1_G.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Liver_20Gy1_SO4.s.md.ir.br.bam Liver_20Gy1_SO4
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Panc_8Gy1_BO.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Panc_8Gy1_SO1.s.md.ir.br.bam Panc_8Gy1_SO1
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Panc_8Gy1_BO.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Panc_8Gy1_SO3.s.md.ir.br.bam Panc_8Gy1_SO3
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Panc_8Gy1_BO.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Liver_8Gy1_SO3.s.md.ir.br.bam Liver_8Gy1_SO3
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Panc_8Gy1_BO.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Liver_8Gy1_SO5.s.md.ir.br.bam Liver_8Gy1_SO5
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Liver_2Gy_2_G.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Panc_2Gy2_SO2.s.md.ir.br.bam Panc_2Gy2_SO2
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Liver_2Gy_2_G.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Liver_2Gy2_SO1.s.md.ir.br.bam Liver_2Gy2_SO1
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Liver_2Gy_2_G.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Liver_2Gy2_SO2.s.md.ir.br.bam Liver_2Gy2_SO2
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Liver_2Gy_2_G.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Liver_2Gy2_SO4.s.md.ir.br.bam Liver_2Gy2_SO4
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Panc_C3_BO.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/C3SO3.s.md.ir.br.bam C3SO3
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Panc_C3_BO.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Liver_C3SO1.s.md.ir.br.bam Liver_C3SO1
sh 00_script.sh /home/users/team_projects/Radiation_signature/02_bam/ Panc_C3_BO.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Liver_C3SO2.s.md.ir.br.bam Liver_C3SO2
