/home/users/jhyouk/81_filter_test_LADC/11_universe_filter/000_universal_annotation_filter_human_radiation.sh hs_study5_colon_IR_HCIR1_SC1 snp hg19
/home/users/jhyouk/81_filter_test_LADC/11_universe_filter/000_universal_annotation_filter_human_radiation.sh hs_study5_colon_IR_HCIR1_SC2 snp hg19
/home/users/jhyouk/81_filter_test_LADC/11_universe_filter/000_universal_annotation_filter_human_radiation.sh hs_study5_colon_IR_HCIR1_SC6 snp hg19
/home/users/jhyouk/81_filter_test_LADC/11_universe_filter/000_universal_annotation_filter_human_radiation.sh hs_study5_colon_control_HCNor1_SC4 snp hg19
/home/users/jhyouk/81_filter_test_LADC/11_universe_filter/000_universal_annotation_filter_human_radiation.sh hs_study5_colon_control_HCNor1_SC5 snp hg19
