/home/users/team_projects/Radiation_signature/02_bam/N1-S4.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/N1spleen.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/B8.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/B3P16_0Gy_4.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Spleen_m3.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_lung_sham_SO4.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_sham.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_lung_sham_SO5.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_sham.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_lung_IR_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_IR.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_SI_sham_SO2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_2nd_sham.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_SI_sham_SO3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_2nd_sham.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_pancreas_IR_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_IR.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_lung_sham_SO3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_sham.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_lung_IR_SO2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_IR.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_pancreas_IR_SO2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_IR.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_pancreas_sham_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_sham.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study1_pancreas_Lowdose_SO4.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/L3_Germline.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study2_pancreas_8by1Gy_SO4.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Panc_8Gy1_BO.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study2_pancreas_8by1Gy_SO2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Panc_8Gy1_BO.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study2_liver_8by1Gy_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Panc_8Gy1_BO.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study2_liver_8by1Gy_SO4.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Panc_8Gy1_BO.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study3_pancreas_Lowdose_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/male_panc_L3BO.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study3_pancreas_Lowdose_SO2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/male_panc_L3BO.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study3_pancreas_Lowdose_SO3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/male_panc_L3BO.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_pancreas_sham_SO2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_sham.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_pancreas_sham_SO3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_sham.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_lung_sham_SO1.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_sham.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_lung_sham_SO2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_sham.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_lung_IR_SO3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_IR.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_lung_IR_SO4.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_IR.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study1_pancreas_lowdose_SO3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/L3_Germline.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study2_liver_IR_8Gy_SO2.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/Panc_8Gy1_BO.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_pancreas_IR_SO3.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/mm_study4_germline_3nd_IR.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_SI_IR_SO1a.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/SI_IR_BOPO.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_SI_IR_SO3a.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/SI_IR_BOPO.s.md.ir.br.bam
/home/users/team_projects/Radiation_signature/02_bam/mm_study4_SI_IR_SO4a.s.md.ir.br.bam /home/users/team_projects/Radiation_signature/02_bam/SI_IR_BOPO.s.md.ir.br.bam
