sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam mm_study1_pancreas_Lowdose_SO4 L3_Germline
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam mm_study2_liver_8by1Gy_SO4 Panc_8Gy1_BO
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam mm_study3_pancreas_Lowdose_SO1 male_panc_L3BO
