scp SV:/home/users/team_projects/Radiation_signature/01_fastq/20Gy_1_S01_S_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/L3_S02_Single_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/L3_S01_Single_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/C3SO3_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/8Gy_2_S02_S_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/8Gy_2_S01_S_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/2Gy_2_S04_S_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/2Gy_2_S03_S_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/20Gy_1_S03_S_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_C3SO2_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_C3SO1_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_8Gy1_SO5_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_8Gy1_SO3_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_2Gy2_SO4_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_8Gy1_SO3_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_8Gy1_SO1_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_2Gy2_SO2_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_20Gy1_SO2_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/male_panc_L3SO5_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/male_panc_L3SO4_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_20Gy1_SO2_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_20Gy1_SO1_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_2Gy2_SO2_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_2Gy2_SO1_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_20Gy1_SO4_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_C3_SO1_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_20Gy_1_G_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/L3_Germline_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_8Gy_2_G_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_2Gy_2_G_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_C3_BO_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_8Gy1_BO_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_8Gy1_BO_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/male_panc_L3BO_R1.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/20Gy_1_S01_S_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/L3_S02_Single_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/L3_S01_Single_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/C3SO3_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/8Gy_2_S02_S_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/8Gy_2_S01_S_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/2Gy_2_S04_S_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/2Gy_2_S03_S_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/20Gy_1_S03_S_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_C3SO2_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_C3SO1_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_8Gy1_SO5_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_8Gy1_SO3_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_2Gy2_SO4_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_8Gy1_SO3_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_8Gy1_SO1_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_2Gy2_SO2_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_20Gy1_SO2_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/male_panc_L3SO5_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/male_panc_L3SO4_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_20Gy1_SO2_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_20Gy1_SO1_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_2Gy2_SO2_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_2Gy2_SO1_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_20Gy1_SO4_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_C3_SO1_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_20Gy_1_G_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/L3_Germline_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_8Gy_2_G_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Liver_2Gy_2_G_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_C3_BO_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_8Gy1_BO_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/Panc_8Gy1_BO_R2.fastq.gz .
scp SV:/home/users/team_projects/Radiation_signature/01_fastq/male_panc_L3BO_R2.fastq.gz .
