sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam mm_study4_SI_IR_SO3 mm_study4_germline_2nd_IR
sh 00_Delly.sh /home/users/team_projects/Radiation_signature/02_bam mm_study4_SI_IR_SO4 mm_study4_germline_2nd_IR
